config/routes.rb
Rails.application.routes.draw do
  # home page points to pages controller, home action
  root to: 'pages#home'
  # routes for devise (extend devise functionality)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # nested resource (each user profile has route for various actions)
  resources :users do
    resource :profile
  end
  # on get request, go to pages controller and run about action
  get 'about', to: 'pages#about'
  # allow only create action from contacts routes
  resources :contacts, only: :create
  # on get request, go to contacts_controller and run new action
  get 'contact-us', to: 'contacts#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # make sure contact form contains these fields
  # ( contact form validations )
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # each profile belongs to user (connects to user class)
  belongs_to :user
  # create association for image (imagemagick avatar)
  has_attached_file :avatar,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  belongs_to :plan
  has_one :profile
  
  attr_accessor :stripe_card_token
  # If Pro user passes validations (email, password, etc. ).
  # then call Stripe and tell Stripe to set up a subscription
  # upon charging the customer's card
  # Stripe responds back with customer data
  # we store customer.id as the customer token and save the user
  def save_with_subscription
    # check if forms passed device validations
    if valid?
      # save customer token to db
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Whitelist the following form fields so that we can process them if coming from
  # a devise sign up form
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # Rails looks for corresponding view file (new.html.erb)
  # when routes.rb calls this action, that's how we display
  # the webpage we want.
  
  # GET request to /contact-us
  # Show new contact form
  def new
    # create a blank contact object (a list with id, name, etc.)
    @contact = Contact.new
  end
  # saves contact form to db
  # POST request to /contacts
  def create
    # mass assign form fields into Contact object
    @contact = Contact.new(contact_params)
    # try to save Contact object to db
    if @contact.save
      # store form fields via parameters into variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # plug variables into Contact Mailer email method and send email
      ContactMailer.contact_email(name, email, body).deliver
      # store success message in flash hash
      flash[:success] = "Message sent!"
      # redirect to new action
      redirect_to contact_us_path
    else
      # if Contact object doesn't save
      # store errors in flash hash and redirect to the new action
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to contact_us_path
    end
  end
  
  private
    # to collect data from form, we need to use
    # strong parameters and whitelist the form fields
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET request for / (homepage)
  # Pro plan id in Plan db is 1, Basic plan id is 2
  def home
    # Plan.find(id) returns the record from Plan db
    # These variables will be accessible in home.html.erb file
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end
  
  def about
    
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  # Make sure user is logged in before executing any actions
  before_action :authenticate_user!
  # Make sure user is executing actions on his account
  before_action :check_current_user
  
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
    # Create a profile instance to be used in our profile form
    @profile = Profile.new
  end
  # POST to /users/:user_id/profile
  def create
    # Ensure that we have the user who is filling out form
    @user = User.find(params[:user_id])
    # Create profile linked to this specific user
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile created successfully."
      redirect_to user_path(id: params[:user_id])
    else
      flash[:danger] = "Something went wrong. Please try again!"
      render action: :new
    end
  end
  # GET to /users/:user_id/profile/edit
  def edit
    # Retrieve user's existing profile so user can see current form
    @profile = User.find(params[:user_id]).profile
  end
  # PATCH/PUT to /users/:user_id/profile 
  def update
    # Retrieve user's profile from db
    @profile = User.find(params[:user_id]).profile
    # Update the profile 
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile updated successfully."
      # Redirect user to their profile page
      redirect_to user_path(id: params[:user_id])
    else
      flash[:danger] = "Something went wrong. Please try again!"
      render action: :edit
    end
  end
  
  private
    def profile_params
      # Whitelist forms for security (only accept these params in our db)
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title,
                                      :phone_number, :contact_email, :description)
    end
    def check_current_user
      @user = User.find(params[:user_id])
      redirect_to root_path unless @user == current_user
    end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new
  
  def create
    # extend default device gem behavior so that
    # users signing up with the Pro account (plan ID 2)
    # save with a special Stripe subscription function
    # otherwise devise signs up user as usual
    super do |resource|
      # check if there are plan parameters ( in url )
      if params[:plan]
        resource.plan_id = params[:plan]
        # check if user's plan id is Pro
        if resource.plan_id == 2
          # do a "special save"
          resource.save_with_subscription
        else
          # user is coming from Basic form
          # just save them normally
          resource.save
        end
      end
    end
  end
  
  private
    def select_plan
      unless (params[:plan] == '1' or params[:plan] == '2')
        flash[:notice] = "Please select a membership plan to sign up."
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # Make sure the user is logged in before showing any profiles
  before_action :authenticate_user!
  
  # GET to /users
  def index
    # Get all users from db
    # Put the user and profiles table together into one query
    # to minimize server requests
    @users = User.includes(:profile)
  end
  
  # GET to /users/:id
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def job_title_icon
    if @user.profile.job_title == "Developer"
      "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.job_title == "Entrepreneur"
      "<i class='fa fa-rocket'></i>".html_safe
    elsif @user.profile.job_title == "Investor"
      "<i class='fa fa-dollar'></i>".html_safe
    end
  end
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="well contact">
        <h2>Contact Us</h2>
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
            
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
          
          <%= f.submit 'Submit', class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevMatch</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <!-- meta tag to hold stripe public key -->
    <%= tag :meta, :name => "stripe-key" , :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
      <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class='container'>
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">
            <%= link_to root_path, class: "navbar-brand" do %>
              <i class="fa fa-group"></i>
              DevMatch
            <% end %>
          </div>
          <div class="collapse navbar-collapse" id="main-nav-collapse">
            <div class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-outline navbar-btn' %>
              <% else %>
                <%= link_to "Log in", new_user_session_path, class: 'btn btn-primary btn-outline navbar-btn' %>
              <% end %>
            </div>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "Community", users_path %></li>
                <li><%= link_to "My Account", edit_user_registration_path %></li>
              <% end %>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact Us", contact_us_path %></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div>
      </nav>
    <div class="container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div , msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    <%= yield %>  
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About Us</h1>
    <p>Welcome to DevMatch! Our mission is to provide an exclusive community for
    developers, entrepreneurs and investors to meet and colaborate together.</p>
</div>

app/views/pages/home.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <% if user_signed_in? %>
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "devmatch_banner.png", class: 'banner' %>
      <% if @user.profile %>
        <div class="carousel-caption">
          <h1 class="text-center"><%= "Hello, #{@user.profile.first_name} #{@user.profile.last_name}!" %></h1>
          <%= image_tag @user.profile.avatar.url, class: 'avatar-home-img' %>
          <br>
          <span class="home job-title-icon"><%= job_title_icon %></span>
        </div>
      <% else %>
      <div class="carousel-caption">
        <h1 class="text-center">It looks like you don't have a profile yet</h1>
        <h3 class="text-center">Create a profile now using tools below</h3>
      </div>
      <% end %>
    </div>
  </div>
  <% else %>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag "devmatch_banner.png", class: 'banner' %>
        <div class="carousel-caption">
          <h1>Welcome to DevMatch</h1>
          <h3>A membership site where entrepreneurs, investors and developers meet</h3>
        </div>
      </div>
      <div class="item">
        <%= image_tag "devmatch_banner.png", class: 'banner' %>
        <div class="carousel-caption">
          <h1>Find the person you were looking for</h1>
          <h3>Our community helps you to discover individuals to help you succeed</h3>
        </div>
      </div>
      <div class="item">
        <%= image_tag "devmatch_banner.png", class: 'banner' %>
        <div class="carousel-caption">
          <h1>Create your profile now</h1>
          <h3>Choose one of the plans below and join our lovely community</h3>
        </div>
      </div>
    </div>
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  <% end %>
  

  
</div>
<div class="container home-signup-links">
  <div class="row">
    <% if user_signed_in? %>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Profile</h2>
          <!-- Check if user has a profile created already -->
          <% if current_user.profile %>
            <!-- Show view and edit options -->
            <%= link_to "Edit profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
            <%= link_to "View profile", user_path(id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          <!-- User has not created a profile yet, show them the option to do so -->
          <% else %>
            <p class="text-center">Create your profile to allow community members to discover you.</p>
            <%= link_to "Create profile", new_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Community</h2>
          <p class="text-center">Visit our lovely community to meet other developers, entrepreneurs and investors.</p>
          <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
        </div>
      </div>
    <% else %>
      <!-- basic sign up form -->
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Basic membership link</h2>
          <h4 class="text-center">Sign up for free and get basic access to the community.</h4>
          <br>
          <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: "btn btn-primary btn-lg btn-block" %>
        </div>
      </div>
      <!-- pro sign up form -->
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Pro membership link</h2>
          <h4 class="text-center">Sign up for the Pro account for just $9.99/month and get full access to the community and contact information.</h4>
          <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: "btn btn-success btn-lg btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
  
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true} do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
  
  
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Edit Your Profile</h1>
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Be a part of the DevMatch community and
    fill out your profile</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">The DevMatch Community</h1>
      <p class="text-center">Users must have a profile form created in order to appear here.</p>
      <ul class="list-unstyled">
        <!-- make sure user has a profile before displaying it -->
        <% @users.each do |user| %>
          <% if user.profile %>
            <li>
              <div class="well row user-index-well <%= cycle('white-bg', '') %>">
                <div class="col-sm-4 text-center">
                  <% if user.profile.avatar %>
                    <%= link_to user do %>
                      <%= image_tag user.profile.avatar.url, class: 'avatar-show-img' %>
                    <% end %>  
                  <% end %>
                </div>
                <div>
                  <%= link_to user do %>
                    <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                  <% end %>
                  <h4><%= user.profile.job_title %></h4>
                  <!-- check if user's account is Pro -->
                  <% if user.plan.id == 2 %>
                    <!-- add a pro label -->
                    <span class="label label-danger">Pro</span>
                  <% end %>
                </div>
              </div>
            </li>
          <br>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="text-center">
      <%= image_tag @user.profile.avatar.url, class: 'avatar-show-img' %>
      <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
      <h3><%= @user.profile.job_title %></h3>
      <span class="users job-title-icon"><%= job_title_icon %></span>
      <div class="well profile-block profile-bio">
        <h3>Bio</h3>
        <%= @user.profile.description %>
      </div>
      <% if current_user.plan_id == 2 %>
        <div class="well profile-block profile-contact">
          <h3>Contact</h3>
          <b>Phone number:</b> <%= @user.profile.phone_number %>
          <br>
          <b>Email:</b> <%= @user.profile.contact_email %>
          <br>
        </div>
      <% end %>
  </div>
</div>